### PR TITLE
Fixed the build and added some optimisations.

### PR DESCRIPTION
**Pull request by anryko**

### CODE REVIEW

**Comment by anryko** [comment]
Reduced image size from 988MB to 713MB.
Better optimizations are possible by introducing two phase build: Build binaries with all the `*-dev` dependencies installed and then move binary artifacts to the new clean image.

**Comment by anryko** [comment]
- Reduced size to 524MB.
- MacOS support: On MacOS docker is on native so you cant share `/dev/net/tun` and running in `host` networking mode makes no difference. Had to limit local OS ports and explicitly map them to local interface ports.

**Comment by anryko** [comment]
- Updated gnurl to 7.57.0
- Added possibility and documentation on how to run multiple containers on same docker host.

**Comment by compiaffe** [comment]
@anryko Just realised somebody was actually using this. Great work reducing the image size. 
I haven't looked into this in months, so will need to take some time to run it on my side. I understand some development is running on gitlab nowadays? We might want to move this repo there and likely get an automated build pushed to hub.docker.io...
More on the weekend!

**Pull request merged**
